[package]
name = "buukuru"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
scraper = "0.19.0"
regex = "1.7.0"
zip = "2.1.3"
walkdir = "2"

[profile.release]
opt-level = "z"
strip = true