[package]
name = "buukuru"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
scraper = "0.19.0"
epub-builder = "0.7"

[profile.release]
opt-level = "z"
strip = true